function [fitresult, gof, xData, yData] = in_and_out_degree_distribution(indeg, outdeg, sizes)
%CREATEFIT(INDEG,OUTDEG)
%  Create a fit.
%
%  Data for 'In-and-out_degree_distribution' fit:
%      X Input : indeg
%      Y Output: outdeg
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-May-2016 14:42:23


%% Fit: 'In-and-out_degree_distribution'.
[xData, yData, size] = prepareCurveData( indeg, outdeg, sizes);

% Set up fittype and options.
ft = fittype( 'rat11' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.162182308193243 0.794284540683907 0.311215042044805];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'In-and-out_degree_distribution' );
scatter(outdeg,indeg,sizes);
hold on;
h = plot( fitresult);
legend( h, 'Out-degree vs. In-degree', 'In-and-out_degree_distribution', 'Location', 'NorthEast' );
% Label axes
xlabel 'Questions Answered'
ylabel 'Questions Asked'
grid on


